---
- name: add /etc/ssh/sshd_config
  template: >
    src=etc-ssh-sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root group=root mode=0644
  notify:
    - ssh restart
  tags:
    - common:security

- name: add /etc/ssh/ssh_config
  copy: >
    src=etc-ssh-ssh_config
    dest=/etc/ssh/ssh_config
    owner=root group=root mode=0644
  tags:
    - common:security

- name: add /etc/security/limits.conf
  copy: >
    src=etc-security-limits.conf
    dest=/etc/security/limits.conf
    owner=root group=root mode=0644
  tags:
    - common:security

- name: add /etc/apt/apt.conf.d/10periodic
  copy: >
    src=etc-apt-apt.conf.d-10periodic
    dest=/etc/apt/apt.conf.d/10periodic
    owner=root group=root mode=0644
  tags:
    - common:security

- name: add /etc/apt/apt.conf.d/50unattended-upgrades
  template: >
    src=etc-apt-apt.conf.d-50unattended-upgrades
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root group=root mode=0644
  tags:
    - common:security

- name: add /etc/iptables.rules
  template: >
    src=etc-iptables.rules
    dest=/etc/iptables.rules
    owner=root group=root mode=0644
  notify:
    - load iptables
  tags:
    - common:security

- name: add /etc/if-pre-up.d and /etc/if-post-down.d iptables-restore
  copy: >
    src=etc-network-if-iptables-restore
    dest=/etc/network/{{ item }}/iptables-restore
    owner=root group=root mode=0755
  with_items:
    - if-pre-up.d
    - if-post-down.d
  notify:
    - load iptables
  tags:
    - common:security

- name: add /etc/fail2ban/jail.local
  template: >
    src=etc-fail2ban-jail.local.j2
    dest=/etc/fail2ban/jail.local
    owner=root group=root mode=0644
  notify:
    - fail2ban restart
  tags:
    - common:security

- name: add /etc/fail2ban/filter.d/nginx.conf
  copy: >
    src=etc-fail2ban-filter.d-nginx.conf
    dest=/etc/fail2ban/filter.d/nginx.conf
    owner=root group=root mode=0644
  notify:
    - fail2ban restart
  tags:
    - common:security
