---
- name: install expect
  apt: pkg=expect state=installed update_cache=yes cache_valid_time=3600
  tags:
    - php:pear-pecl

- name: add /tmp/go-pear.phar
  get_url: >
    url=http://pear.php.net/go-pear.phar
    dest=/tmp/go-pear.phar mode=0740
  tags:
    - php:pear-pecl

- name: copy and execute install-pear.expect script
  script: install-pear.expect
  tags:
    - php:pear-pecl

- name: install pear packages
  shell: pear install {{ item }}
  with_items: $phpPearPackages
  when: phpPearPackages is defined
  tags:
    - php:pear-pecl

- name: install pecl packages
  shell: pecl install {{ item }}
  with_items: $phpPeclPackages
  when: phpPeclPackages is defined
  tags:
    - php:pear-pecl
