---
- name: copy and execute zend-optimzer-plus.sh
  script: zend-optimzer-plus.sh
  tags:
    - php:zend-optimizer-plus

- name: add /etc/php5/mods-available/opcache.ini
  template: >
    src=etc-php5-mods-available-opcache.ini.j2
    dest=/etc/php5/mods-available/opcache.ini
    owner=root group=root mode=0644
  when: "phpInstallVersion == 5.4"
  notify: php5-fpm reload
  tags:
    - php:zend-optimizer-plus

- name: add /etc/php5/conf.d/00-opcache.ini symlink
  file: >
    src=/etc/php5/mods-available/opcache.ini
    dest=/etc/php5/conf.d/00-opcache.ini
    owner=root group=root state=link
  when: "phpInstallVersion == 5.4"
  tags:
    - php:zend-optimizer-plus

- name: add /etc/php5/conf.d/opcache.ini
  template: >
    src=etc-php5-mods-available-opcache.ini.j2
    dest=/etc/php5/conf.d/opcache.ini
    owner=root group=root mode=0644
  when: "phpInstallVersion != 5.4"
  notify: php5-fpm reload
  tags:
    - php:zend-optimizer-plus
